# Configuration for aggregation of residential sector

period_step: 5 # Number of years between model periods

# Future model planning periods
model_periods:
  - 2021
  - 2025
  - 2030
  - 2035
  - 2040
  - 2045
  - 2050

weather_year: 2018 # For normalised timeseries data only
base_year: 2022 # Default year to pull data from
timezone: 'EST'

global_discount_rate: 0.05

# Currency, data costs are exchanged and inflated in post processing
final_currency: 'CAD' # Not configured to output currencies other than CAD yet
final_currency_year: 2020
inflation_index: 'gdp_deflator' # gdp_deflator, general_cpi, energy_and_petroleum, industrial, construction_non_residential

# Set DSD to zero if less than this times hourly average (i.e. dsd(h) = 0 if dsd(h) < tol * mean(dsd))
# For computational reasons
dsd_tolerance: 0.02

sqlite_schema: "canoe_schema.sql"
sqlite_database: "residential.sqlite"
excel_template: "Template spreadsheet (make a copy).xlsx"
excel_output: "residential.xlsx"

## Aggregation switches
force_wipe_database: true # Forces clearing of all data in database prior to aggregation
force_generate_weather_maps: true # Force regeneration of weather maps instead of using locally cached versions
force_download: false # Forces downloading data again instead of using cached versions
show_plots: true
include_dsd: true # Aggregating DSDs is slow
include_imports: true # Aggregates dummy import technologies for fuels
include_emissions: false
include_furnace_fans: false # Whether to include electricity consumption of fans in space heating
simplify_model: false # Reduces to simple model. Current behaviour wipes DSDs so might as well skip those
clone_to_xlsx: false

nrcan_url: "https://oee.nrcan.gc.ca/corporate/statistics/neud/dpa/data_e/downloads/comprehensive/Excel/<y>/res_<r>_e_<t>.xls"
nrcan_reference: 'Natural Resources Canada, (2020). Comprehensive Energy Use Database. https://oee.nrcan.gc.ca/corporate/statistics/neud/dpa/menus/trends/comprehensive_tables/list.cfm'
handbook_reference: 'Natural Resources Canada, (2020). Energy Use Data Handbook Tables. https://oee.nrcan.gc.ca/corporate/statistics/neud/dpa/menus/trends/handbook/tables.cfm'

aeo_reference: 'EIA. (2025, April 15). Download the National Energy Modeling System (NEMS). rsmess [dataset]. https://www.eia.gov/outlooks/aeo/info_nems_archive.php'
aeo_updated_reference: "EIA. (2023). Updated Buildings Sector Appliance and Equipment Costs and Efficiency—Reference case [dataset]. https://www.eia.gov/analysis/studies/buildings/equipcosts/"
aeo_data_year: 2025
aeo_currency_year: 2022
aeo_currency: 'USD'

statcan_reference: "Statistics Canada, (2025, January 21). Projected population, by projection scenario, age and sex, as of July 1. https://www150.statcan.gc.ca/t1/tbl1/en/cv.action?pid=1710005701"
statcan_data_year: 2025

epa_reference: "US EPA. (2023, March). GHG Emission Factors Hub [Overviews and Factsheets]. https://www.epa.gov/climateleadership/ghg-emission-factors-hub"
epa_year: 2025 # Check if GWP factors have changed and update below
epa_url: 'https://www.epa.gov/system/files/other-files/2025-01/ghg-emission-factors-hub-2025.xlsx'
emission_commodity: 'CO2eq'
emission_activity_units: 'ktCO2eq/PJ'

conversion_factors:
  epa_units:
    'CO2': 0.948 # kg/MMBtu to kt/PJ
    'CH4': 0.000948 # g/MMBtu to kt/PJ
    'N2O': 0.000948 # g/MMBtu to kt/PJ
  gwp:
    'CO2': 1 # to CO2eq 100y GWP
    'CH4': 28 # to CO2eq 100y GWP
    'N2O': 265 # to CO2eq 100y GWP
  efficiency:
    'EER': 0.293 # kBtu/kWh to PJ/PJ
  lighting:
    'efficacy': 0.0317 # lm/W to Glmy/PJ
    'lifetime': 1.142E-4 # hours to years 1/8760
    'cost': 1 # $/klm to M$/Glm
  activity:
    'kwh': 3.6e-9 # kWh to PJ
  cost:
    'invest': 0.001 # $/unit to M$/kunit
    'fixed': 0.001 # $/unit.y to M$/kunit.y

furnace_fans:
  output_split: 0.0205 # PJ elc in / PJ heat out, from 6 kWh/MMBtu
  efficiency: 0.001
  data_year: 2013
  reference: 'nyserda. (2013, April 15). Gas Furnace Electricity Usage. https://www.taitem.com/wp-content/uploads/tt_furnace_electricity_use_20130507.pdf'

appliances:
  annual_capacity_factor: 0.05 # Arbitrary capacity factor for appliances to ensure peak demand is met

lighting: 
  annual_capacity_factor: 0.0667 # 1.6/24
  acf_reference: "DOE. (2012). Residential Lighting End-Use Consumption Study: Estimation Framework and Initial Estimates. https://www1.eere.energy.gov/buildings/publications/pdfs/ssl/2012_residential-lighting-study.pdf"
  acf_data_year: 2012
  acf_note: "1.6 hours per day national average usage from US."
  on_stock_ref: "IESO. (2018). 2018 Ontario Residential End-Use Survey. IESO. https://ieso.ca/-/media/Files/IESO/Document-Library/research/Ontario-Residential-End-Use-Survey.ashx"
  usage_ref: "Statistics Canada. (2018, June 27). Use of energy-saving lights, Canada and provinces. https://www150.statcan.gc.ca/t1/tbl1/en/tv.action?pid=3810004801"
  input_comm: 'electricity'

# Categorising NRCan housing stocks
housing_categories:
  single_family: "single detached+single attached+mobile homes"
  multi_family: "apartments"

resstock:
  url: https://oedi-data-lake.s3.amazonaws.com/nrel-pds-building-stock/end-use-load-profiles-for-us-building-stock/2024/resstock_amy2018_release_2/timeseries_aggregates/by_state/upgrade=16/state=<s>/<f>
  housing_files:
    'mobile homes': 'up16-<s>-mobile_home.csv'
    'apartments': 'up16-<s>-multi-family_with_5plus_units.csv'
    'single attached': 'up16-<s>-single-family_attached.csv'
    'single detached': up16-<s>-single-family_detached.csv
  reference: 'NREL. (2024). ResStock-NREL (amy2018, v2, upgrade 16). https://data.openei.org/s3_viewer?bucket=oedi-data-lake&prefix=nrel-pds-building-stock%2Fend-use-load-profiles-for-us-building-stock%2F2024%2Fresstock_amy2018_release_2%2Ftimeseries_aggregates%2Fby_state%2Fupgrade%3D16%2F'

weather:
  us_temperature_url: https://www.renewables.ninja/country_downloads/US/renewables_ninja_country_US_temperature_merra-2_pop-wtd.csv
  us_humidity_url: https://www.renewables.ninja/country_downloads/US/renewables_ninja_country_US_humidity_merra-2_pop-wtd.csv
  ca_temperature_url: https://www.renewables.ninja/country_downloads/CA/renewables_ninja_country_CA_temperature_merra-2_pop-wtd.csv
  ca_humidity_url: https://www.renewables.ninja/country_downloads/CA/renewables_ninja_country_CA_humidity_merra-2_pop-wtd.csv
  reference: 'Staffell et al. (2023) https://doi.org/10.1038/s41560-023-01341-5 https://www.renewables.ninja/'