# Configuration for residential sector

period_step: 5

# Must be in ascending order along with all data in tables!
model_periods:
  - 2025
  - 2030
  - 2035
  - 2040
  - 2045
  - 2050
  
base_year: 2020

global_discount_rate: 0.05

show_plots: true
skip_dsd: false # Aggregating DSDs is slow so might want to skip sometimes

nrcan_url: "https://oee.nrcan.gc.ca/corporate/statistics/neud/dpa/data_e/downloads/comprehensive/Excel/<y>/res_<r>_e_<t>.xls"
nrcan_reference: 'Natural Resources Canada, (2020). Comprehensive Energy Use Database. https://oee.nrcan.gc.ca/corporate/statistics/neud/dpa/menus/trends/comprehensive_tables/list.cfm'
handbook_reference: 'Natural Resources Canada, (2020). Energy Use Data Handbook Tables. https://oee.nrcan.gc.ca/corporate/statistics/neud/dpa/menus/trends/handbook/tables.cfm'

aeo_reference: 'EIA. (2023). Updated Buildings Sector Appliance and Equipment Costs and Efficiency—Reference case [dataset]. https://www.eia.gov/analysis/studies/buildings/equipcosts/'
aeo_data_year: 2023
aeo_currency_year: 2022
aeo_currency: 'USD'

statcan_reference: "Statistics Canada, (2022, August 22). Projected population, by projection scenario, age and sex, as of July 1. https://www150.statcan.gc.ca/t1/tbl1/en/cv.action?pid=1710005701"
statcan_data_year: 2022

epa_reference: "US EPA. (2023, March). GHG Emission Factors Hub [Overviews and Factsheets]. https://www.epa.gov/climateleadership/ghg-emission-factors-hub"
epa_year: 2023
emissions_commodity: 'CO2eq'
emission_activity_units: 'ktCO2eq/PJ'

conversion_factors:
  epa_units:
    'CO2': 0.948 # kg/MMBtu to kt/PJ
    'CH4': 0.000948 # g/MMBtu to kt/PJ
    'N2O': 0.000948 # g/MMBtu to kt/PJ
  gwp:
    'CO2': 1 # to CO2eq 100y GWP
    'CH4': 25 # to CO2eq 100y GWP
    'N2O': 298 # to CO2eq 100y GWP
  efficiency:
    'EER': 0.293 # kBtu/kWh to PJ/PJ
  lighting:
    'efficacy': 0.0317 # lm/W to Glmy/PJ
    'lifetime': 1.142E-4 # hours to years 1/8760
    'cost': 1 # $/klm(y) to M$/Glm(y)
  activity:
    'kwh': 3.6e-9 # kWh to PJ

furnace_fans:
  output_split: 0.0205 # PJ elc in / PJ heat out, from 6 kWh/MMBtu
  output_commodity: 'R_ELC'
  efficiency: 0.001
  reference: 'nyserda. (2013, April 15). Gas Furnace Electricity Usage. https://www.taitem.com/wp-content/uploads/tt_furnace_electricity_use_20130507.pdf'

appliances:
  annual_capacity_factor: 0.05 # Arbitrary capacity factor for appliances to ensure peak demand is met
  other_tech: 'R_APP_OTH'

lighting: 
  annual_capacity_factor: 0.0667 # 1.6/24
  acf_reference: "DOE. (2012). Residential Lighting End-Use Consumption Study: Estimation Framework and Initial Estimates. https://www1.eere.energy.gov/buildings/publications/pdfs/ssl/2012_residential-lighting-study.pdf"
  acf_data_year: 2012
  acf_note: "1.6 hours per day national average usage from US."
  on_stock_ref: "IESO. (2018). 2018 Ontario Residential End-Use Survey. IESO. https://ieso.ca/-/media/Files/IESO/Document-Library/research/Ontario-Residential-End-Use-Survey.ashx"
  usage_ref: "Statistics Canada. (2018, June 27). Use of energy-saving lights, Canada and provinces. https://www150.statcan.gc.ca/t1/tbl1/en/tv.action?pid=3810004801"
  input_comm: 'electricity'

# Categorising NRCan housing stocks
housing_categories:
  single_family: "single detached+single attached+mobile homes"
  multi_family: "apartments"

resstock:
  url: https://oedi-data-lake.s3.amazonaws.com/nrel-pds-building-stock/end-use-load-profiles-for-us-building-stock/2022/resstock_amy2018_release_1.1/timeseries_aggregates/by_state/upgrade=10/state=<s>/<f>
  housing_files:
    'mobile homes': 'up10-<s>-mobile_home.csv'
    'apartments': 'up10-<s>-multi-family_with_5plus_units.csv'
    'single attached': 'up10-<s>-single-family_attached.csv'
    'single detached': up10-<s>-single-family_detached.csv
  reference: 'NREL. (2021, October). ResStock-NREL (amy2018, v1.1, upgrade 10). https://data.openei.org/s3_viewer?bucket=oedi-data-lake&prefix=nrel-pds-building-stock%2Fend-use-load-profiles-for-us-building-stock%2F2022%2Fresstock_amy2018_release_1.1%2Ftimeseries_aggregates%2Fby_state%2Fupgrade%3D10%2F'
  year: 2018

weather:
  us:
    url: 'https://www.ncei.noaa.gov/data/global-hourly/access/2018/<st>.csv'
    reference: 'National Centers for Environmental Information. (2018). Integrated Surface Dataset (Global). https://www.ncei.noaa.gov/access/search/data-search/global-hourly'
  canada:
    url: 'https://dd.weather.gc.ca/climate/observations/hourly/csv/<r>/climate_hourly_<r>_<st>_2020_P1H.csv'
    reference: 'Meteorological Services of Canada. (<y>). Hourly Climate Observations - Web Accessible Folder. https://dd.weather.gc.ca/climate/observations/hourly/csv/'